# Permalinks
permalink: /:year-:month-:day/:title

# Setup
title: Tairy's Blog
paginate: 10
baseurl: ""
url: "http://tairy.me"

# Assets
sass:
  sass_dir: _sass
  style: :compressed

# Build settings
markdown: kramdown

plugins:
  - jekyll-paginate

source: src
destination: target
timezone: Asia/Shanghai 